jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.417'

    - name: Build Solution
      run: dotnet build MinidimSharp.sln --configuration Release

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: bin/Release/net7.0-windows/*

    - name: Create Zip
      run: |
        Compress-Archive -Path bin/Release/net7.0-windows/* -DestinationPath my-artifact.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}  # Use the tag name as the release name
        tag_name: ${{ github.ref_name }}
        files: ./my-artifact.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
