name: .NET Build and Release

permissions:
  contents: write

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build Solution
      run: dotnet build MinidimSharp.sln --configuration Release

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MinidimSharp
        path: bin/Release/net7.0-windows/*

    - name: Create Zip
      run: |
        Compress-Archive -Path bin/Release/net7.0-windows/* -DestinationPath MinidimSharp.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: MinidimSharp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.MINIDIMSHARP_SECRET }}