jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        include-prerelease: false

    - name: Build with dotnet
      run: dotnet build --configuration Debug

    - name: dotnet publish
      run: dotnet publish -c Release -o "${{env.GITHUB_WORKSPACE}}\MinidimSharp"

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.GITHUB_WORKSPACE}}\MinidimSharp
