name: .NET Build and Release

permissions:
  contents: write

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build Solution
      run: dotnet build MinidimSharp.sln --configuration Release

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MinidimSharp
        path: bin/Release/net7.0-windows/*

    - name: Create Zip
      run: |
        Compress-Archive -Path bin/Release/net7.0-windows/* -DestinationPath MinidimSharp.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.secrets.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 }}