name: .NET Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'draft'  # Trigger the workflow when you push this tag

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.417'

    - name: Build Solution
      run: dotnet build MinidimSharp.sln --configuration Release

      - name: Create Release
      if: github.ref == 'refs/tags/draft'
      uses: softprops/action-gh-release@v1
      with:
        name: 'MinidimSharp v0.2'  # Manually setting release name
        tag_name: ${{ github.ref }}
        files: bin\Release\net7.0-windows\
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
